Add default url and config
onflow/flixkit-go pull request #3
Opened 2023-07-14 21:54 UTC by chasefleming

2023-07-17 20:48 UTC, bjartek requested changes

2023-07-17 20:48 UTC, bjartek commented on flixkit.go
> +	GetFlixRaw(templateName string) (string, error)
It is best practise to add context as the first parameters to these kind of apis in order to be able to cancel a request chain, can we add that?

2023-07-18 00:12 UTC, bjartek approved these changes

2023-07-18 00:17 UTC, nvdtf approved these changes

2023-07-18 17:12 UTC, merged